[build]
  command = "bash ./netlify/flutter.sh"
  publish = "academia_app/build/web"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
