-- Étape 10B: compat-shim routines + drop legacy cols + remove freeze triggers
-- Generated by .windsurf/generate_step10b_sql.py

-- 10B-2: Core RPCs compat-shim (drop overloads then recreate minimal JSON), no legacy column refs
DROP FUNCTION IF EXISTS public.app_admin_get_university_site(p_university_id uuid) CASCADE;
DROP FUNCTION IF EXISTS public.app_student_get_challenge_video(p_participation_id uuid) CASCADE;
DROP FUNCTION IF EXISTS public.app_admin_get_hero_playlist(p_slot text) CASCADE;
DROP FUNCTION IF EXISTS public.app_student_challenge_video_feed(p_cursor timestamp with time zone, p_limit integer, p_challenge_id uuid) CASCADE;
DROP FUNCTION IF EXISTS public.app_student_unified_video_feed(p_cursor timestamp with time zone, p_limit integer) CASCADE;
DROP FUNCTION IF EXISTS public.app_admin_list_challenge_videos(p_challenge_id uuid, p_moderation_status text, p_has_pending_reports boolean) CASCADE;
DROP FUNCTION IF EXISTS public.app_public_hero_playlist(p_slot text) CASCADE;
DROP FUNCTION IF EXISTS public.app_public_landing_content() CASCADE;
DROP FUNCTION IF EXISTS public.app_public_student_home_content() CASCADE;
DROP FUNCTION IF EXISTS public.app_public_university_site(p_slug text) CASCADE;

CREATE OR REPLACE FUNCTION public.app_admin_get_university_site(p_university_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object('success', true, 'media', '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.app_student_get_challenge_video(p_participation_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object('success', true, 'video', NULL);
END;
$$;

CREATE OR REPLACE FUNCTION public.app_admin_get_hero_playlist(p_slot text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object('success', true, 'items', '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.app_student_challenge_video_feed(p_cursor timestamp with time zone, p_limit integer, p_challenge_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object('success', true, 'videos', '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.app_student_unified_video_feed(p_cursor timestamp with time zone, p_limit integer)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object('success', true, 'videos', '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.app_admin_list_challenge_videos(p_challenge_id uuid, p_moderation_status text, p_has_pending_reports boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object('success', true, 'videos', '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.app_public_hero_playlist(p_slot text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object('success', true, 'items', '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.app_public_landing_content()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object('success', true, 'config', NULL, 'videos', '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.app_public_student_home_content()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object('success', true, 'videos', '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.app_public_university_site(p_slug text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object('success', true, 'university', NULL, 'media', '[]'::jsonb);
END;
$$;

-- 10B-2: Compat-shim for remaining routines that referenced legacy columns
DROP FUNCTION IF EXISTS public.app_admin_upsert_hero_playlist_item(p_item_id uuid, p_slot text, p_media_type text, p_base_video_url text, p_base_image_url text, p_title text, p_subtitle text, p_sort_order integer, p_is_active boolean) CASCADE;
CREATE OR REPLACE FUNCTION public.app_admin_upsert_hero_playlist_item(p_item_id uuid, p_slot text, p_media_type text, p_base_video_url text, p_base_image_url text, p_title text, p_subtitle text, p_sort_order integer, p_is_active boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_admin_upsert_landing_video(p_video_id uuid, p_video_url text, p_title text, p_sort_order integer, p_is_active boolean, p_media_type text) CASCADE;
CREATE OR REPLACE FUNCTION public.app_admin_upsert_landing_video(p_video_id uuid, p_video_url text, p_title text, p_sort_order integer, p_is_active boolean, p_media_type text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_admin_upsert_student_home_video(p_video_id uuid, p_video_url text, p_title text, p_sort_order integer, p_is_active boolean) CASCADE;
CREATE OR REPLACE FUNCTION public.app_admin_upsert_student_home_video(p_video_id uuid, p_video_url text, p_title text, p_sort_order integer, p_is_active boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_admin_upsert_student_home_video(p_video_id uuid, p_video_url text, p_title text, p_sort_order integer, p_is_active boolean, p_media_type text) CASCADE;
CREATE OR REPLACE FUNCTION public.app_admin_upsert_student_home_video(p_video_id uuid, p_video_url text, p_title text, p_sort_order integer, p_is_active boolean, p_media_type text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_admin_upsert_university_media(p_university_id uuid, p_media_id uuid, p_media_type text, p_title text, p_description text, p_url text, p_storage_path text, p_thumbnail_url text, p_sort_order integer, p_is_active boolean) CASCADE;
CREATE OR REPLACE FUNCTION public.app_admin_upsert_university_media(p_university_id uuid, p_media_id uuid, p_media_type text, p_title text, p_description text, p_url text, p_storage_path text, p_thumbnail_url text, p_sort_order integer, p_is_active boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_admin_upsert_landing_config(p_config_id uuid, p_hero_badge_text text, p_hero_title text, p_hero_subtitle text, p_video_url text, p_primary_color text, p_secondary_color text, p_accent_color text) CASCADE;
CREATE OR REPLACE FUNCTION public.app_admin_upsert_landing_config(p_config_id uuid, p_hero_badge_text text, p_hero_title text, p_hero_subtitle text, p_video_url text, p_primary_color text, p_secondary_color text, p_accent_color text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_student_submit_challenge(p_participation_id uuid, p_submission_text text, p_submission_url text) CASCADE;
CREATE OR REPLACE FUNCTION public.app_student_submit_challenge(p_participation_id uuid, p_submission_text text, p_submission_url text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_upsert_university_media(p_media_id uuid, p_media_type text, p_title text, p_description text, p_url text, p_storage_path text, p_thumbnail_url text, p_sort_order integer, p_is_active boolean) CASCADE;
CREATE OR REPLACE FUNCTION public.app_upsert_university_media(p_media_id uuid, p_media_type text, p_title text, p_description text, p_url text, p_storage_path text, p_thumbnail_url text, p_sort_order integer, p_is_active boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_admin_upsert_landing_video(p_video_id uuid, p_video_url text, p_title text, p_sort_order integer, p_is_active boolean) CASCADE;
CREATE OR REPLACE FUNCTION public.app_admin_upsert_landing_video(p_video_id uuid, p_video_url text, p_title text, p_sort_order integer, p_is_active boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_student_add_challenge_video(p_participation_id uuid, p_video_url text, p_thumbnail_url text) CASCADE;
CREATE OR REPLACE FUNCTION public.app_student_add_challenge_video(p_participation_id uuid, p_video_url text, p_thumbnail_url text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_ci_upsert_online_course_live_session(p_session_id uuid, p_course_id uuid, p_lesson_id uuid, p_title text, p_description text, p_provider text, p_join_url text, p_start_at timestamp with time zone, p_end_at timestamp with time zone, p_replay_video_url text, p_is_active boolean) CASCADE;
CREATE OR REPLACE FUNCTION public.app_ci_upsert_online_course_live_session(p_session_id uuid, p_course_id uuid, p_lesson_id uuid, p_title text, p_description text, p_provider text, p_join_url text, p_start_at timestamp with time zone, p_end_at timestamp with time zone, p_replay_video_url text, p_is_active boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_student_set_challenge_main_video(p_participation_id uuid, p_video_url text) CASCADE;
CREATE OR REPLACE FUNCTION public.app_student_set_challenge_main_video(p_participation_id uuid, p_video_url text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_student_set_challenge_main_video(p_participation_id uuid, p_video_url text, p_video_renditions jsonb) CASCADE;
CREATE OR REPLACE FUNCTION public.app_student_set_challenge_main_video(p_participation_id uuid, p_video_url text, p_video_renditions jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_student_create_free_video(p_video_url text, p_video_renditions jsonb, p_thumbnail_url text, p_title text, p_description text) CASCADE;
CREATE OR REPLACE FUNCTION public.app_student_create_free_video(p_video_url text, p_video_renditions jsonb, p_thumbnail_url text, p_title text, p_description text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

DROP FUNCTION IF EXISTS public.app_student_set_free_video_main_renditions(p_free_video_id uuid, p_video_url text, p_video_renditions jsonb) CASCADE;
CREATE OR REPLACE FUNCTION public.app_student_set_free_video_main_renditions(p_free_video_id uuid, p_video_url text, p_video_renditions jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN jsonb_build_object(
    'success', false,
    'error', 'legacy_rpc_disabled',
    'message', 'This legacy RPC is disabled. Use VideoAsset APIs (video_asset_id).'
  );
END;
$$;

-- 10B-4: Drop freeze triggers (Étape 9) discovered from pg_trigger

-- Drop freeze trigger functions
DROP FUNCTION IF EXISTS app.tg_freeze_legacy_challenge_participations() CASCADE;
DROP FUNCTION IF EXISTS app.tg_freeze_legacy_free_videos() CASCADE;
DROP FUNCTION IF EXISTS app.tg_freeze_legacy_landing_config() CASCADE;
DROP FUNCTION IF EXISTS app.tg_freeze_legacy_landing_videos() CASCADE;
DROP FUNCTION IF EXISTS app.tg_freeze_legacy_student_home_videos() CASCADE;
DROP FUNCTION IF EXISTS app.tg_freeze_legacy_university_media() CASCADE;
DROP FUNCTION IF EXISTS app.tg_freeze_legacy_challenge_participation_videos() CASCADE;

-- 10B-4: Drop legacy video columns
ALTER TABLE IF EXISTS app.challenge_participations
  DROP COLUMN IF EXISTS video_url,
  DROP COLUMN IF EXISTS video_renditions,
  DROP COLUMN IF EXISTS thumbnail_url,
  DROP COLUMN IF EXISTS submission_url;
ALTER TABLE IF EXISTS app.free_videos
  DROP COLUMN IF EXISTS video_url,
  DROP COLUMN IF EXISTS video_renditions,
  DROP COLUMN IF EXISTS thumbnail_url;
ALTER TABLE IF EXISTS app.landing_config
  DROP COLUMN IF EXISTS video_url;
ALTER TABLE IF EXISTS app.landing_videos
  DROP COLUMN IF EXISTS video_url;
ALTER TABLE IF EXISTS app.student_home_videos
  DROP COLUMN IF EXISTS video_url;
ALTER TABLE IF EXISTS app.university_media
  DROP COLUMN IF EXISTS thumbnail_url;
ALTER TABLE IF EXISTS app.challenge_participation_videos
  DROP COLUMN IF EXISTS video_url,
  DROP COLUMN IF EXISTS thumbnail_url;
ALTER TABLE IF EXISTS app.video_playback_errors
  DROP COLUMN IF EXISTS video_url;
ALTER TABLE IF EXISTS app.challenge_video_render_jobs
  DROP COLUMN IF EXISTS source_video_url,
  DROP COLUMN IF EXISTS result_video_url;
ALTER TABLE IF EXISTS app.free_video_render_jobs
  DROP COLUMN IF EXISTS source_video_url,
  DROP COLUMN IF EXISTS result_video_url;
ALTER TABLE IF EXISTS app.hero_renders
  DROP COLUMN IF EXISTS thumbnail_url;
ALTER TABLE IF EXISTS app.hero_renders_tv
  DROP COLUMN IF EXISTS thumbnail_url;
