org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -Dhttp.connectionTimeout=180000 -Dhttp.socketTimeout=180000 -Dorg.gradle.internal.http.connectionTimeout=180000 -Dorg.gradle.internal.http.socketTimeout=180000
android.useAndroidX=true
android.enableJetifier=true

# Kotlin configuration
kotlin_version=2.1.0
